paths:
  # Paths are relative to the program directory
  input_dir: "../data/input/"
  output_dir: "../data/output/"

backtest:
  start_date: "1995-03-01"
  end_date: "1996-03-01"
  train_duration: 21
  interpolation_method: "linear"
  pca_rank: 3
